packages:
  - packages/*
  - docs
  - tauri

catalog:
  '@antfu/eslint-config': ^4.19.0
  '@antfu/ni': ^25.0.0
  '@iconify/json': ^2.2.366
  '@iconify/tailwind4': ^1.0.6
  '@scena/guides': ^0.29.2
  '@scena/ruler': ^0.20.0
  '@tailwindcss/vite': ^4.1.11
  '@tauri-apps/api': ^2
  '@tauri-apps/cli': ^2
  '@tauri-apps/plugin-opener': ^2
  '@types/node': ^22.16.5
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': 13.6.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  esbuild: ^0.24.2
  eslint: ^9.32.0
  eslint-factory: ^0.1.2
  eslint-plugin-format: ^1.0.1
  eslint-plugin-unimport: ^0.1.2
  infinite-viewer: ^0.29.1
  lucide-vue-next: ^0.536.0
  prettier: ^3.6.2
  reka-ui: ^2.4.1
  rolldown: 1.0.0-beta.29
  sass: ^1.89.2
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.11
  taze: ^19.1.0
  tsdown: ^0.13.0
  tw-animate-css: ^1.3.6
  typescript: ^5.8.3
  unplugin-unused: ^0.5.1
  unplugin-vue: ^7.0.0
  vite: ^6.0.3
  vitepress: ^1.6.3
  vue: ^3.5.18
  vue-tsc: ^2.1.10

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
