packages:
  - packages/*
  - docs
  - playground

catalog:
  '@antfu/eslint-config': ^4.19.0
  '@types/node': ^22.16.5
  esbuild: ^0.24.2
  eslint: ^9.32.0
  eslint-factory: ^0.1.2
  eslint-plugin-format: ^1.0.1
  eslint-plugin-unimport: ^0.1.2
  prettier: ^3.6.2
  rolldown: 1.0.0-beta.29
  taze: ^19.1.0
  tsdown: ^0.13.0
  typescript: ^5.8.3
  vue: ^3.5.18

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
